version: "2.1"
services:

    sql-db:
        restart: "always"
        image: sameersbn/postgresql:9.6-2
        healthcheck: { test: "psql --username user --list" }
        logging: { driver: none }
        environment:
            - DB_NAME=test
            - DB_USER=user
            - DB_PASS=pass
        ports:
            - "5432:5432"

    app:
        build:
                context: ./service
                dockerfile: Dockerfile-test
        depends_on:
            sql-db: { condition: service_healthy }
        links: 
            - sql-db
        environment:
            - SQL_DB=user=user dbname=test sslmode=disable port=5432 host=sql-db password=pass
        ports:
            - "8080:8080"
